# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_events_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='going',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='----', max_length=3),
        ),
        migrations.AlterField(
            model_name='events',
            name='day',
            field=models.DateField(null=True),
        ),
    ]
