# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180415_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='going',
        ),
    ]
