# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('Computer Engineering', 'Computer Engineering'), ('Electronics and Telecommunication Engineering', 'Electronics and Telecommunication Engineering'), ('Electronics Engineering', 'Electronics Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Production Engineering', 'Production Engineering'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Information Technology', 'Information Technology')], default='--------', max_length=50),
        ),
    ]
