# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0004_auto_20180415_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='user.png', upload_to='profile pics/'),
        ),
    ]
